### ISSUE TITLE
ARMED state timeout ~10mins + arduino disarm

### ISSUE THREAD

**Issue by TimKeesRensen** [uc-csse/RovVision2#25]
Can we stop sending serial messeges through hw_gate while disarmed, then the arduino can DISARM as well

**Comment by orig74** [comment]
We can but do we need to? I am sending zeros when disarmed.

**Comment by orig74** [comment]
You want me to disarm the ROV after 10 min?

**Comment by TimKeesRensen** [comment]
The thrusters are beeping because the Escs are receiving zeros, if there is no signal at all they disarm and don't beep. so the arduino will stop sending dshot messages when it stops receiving serial signals




Cheers, 




Tim






On Wed, Aug 14, 2019 at 11:44 PM +1200, "Ori" <notifications@github.com> wrote:












You want me to disarm the ROV after 10 min?
